//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
// source code is governed by an MIT-style license described in the LICENSE
// file located in this project's root directory.
//
// See: https://opensource.org/license/mit
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

enum CountryCode {
  AD(custom: false),
  AE(custom: false),
  AF(custom: false),
  AG(custom: false),
  AI(custom: false),
  AL(custom: false),
  AM(custom: false),
  AO(custom: false),
  AQ(custom: false),
  AR(custom: false),
  AS(custom: false),
  AT(custom: false),
  AU(custom: false),
  AW(custom: false),
  AX(custom: false),
  AZ(custom: false),
  BA(custom: false),
  BB(custom: false),
  BD(custom: false),
  BE(custom: false),
  BF(custom: false),
  BG(custom: false),
  BH(custom: false),
  BI(custom: false),
  BJ(custom: false),
  BL(custom: false),
  BM(custom: false),
  BN(custom: false),
  BO(custom: false),
  BQ(custom: false),
  BR(custom: false),
  BS(custom: false),
  BT(custom: false),
  BV(custom: false),
  BW(custom: false),
  BY(custom: false),
  BZ(custom: false),
  CA(custom: false),
  CC(custom: false),
  CD(custom: false),
  CF(custom: false),
  CG(custom: false),
  CH(custom: false),
  CI(custom: false),
  CK(custom: false),
  CL(custom: false),
  CM(custom: false),
  CN(custom: false),
  CO(custom: false),
  CR(custom: false),
  CU(custom: false),
  CV(custom: false),
  CW(custom: false),
  CX(custom: false),
  CY(custom: false),
  CZ(custom: false),
  DE(custom: false),
  DJ(custom: false),
  DK(custom: false),
  DM(custom: false),
  DO(custom: false),
  DZ(custom: false),
  EC(custom: false),
  EE(custom: false),
  EG(custom: false),
  EH(custom: false),
  ER(custom: false),
  ES(custom: false),
  ET(custom: false),
  EU(custom: false),
  FI(custom: false),
  FJ(custom: false),
  FK(custom: false),
  FM(custom: false),
  FO(custom: false),
  FR(custom: false),
  GA(custom: false),
  GB_ENG(custom: false),
  GB_NIR(custom: false),
  GB_SCT(custom: false),
  GB_WLS(custom: false),
  GB(custom: false),
  GD(custom: false),
  GE(custom: false),
  GF(custom: false),
  GG(custom: false),
  GH(custom: false),
  GI(custom: false),
  GL(custom: false),
  GM(custom: false),
  GN(custom: false),
  GP(custom: false),
  GQ(custom: false),
  GR(custom: false),
  GS(custom: false),
  GT(custom: false),
  GU(custom: false),
  GW(custom: false),
  GY(custom: false),
  HK(custom: false),
  HM(custom: false),
  HN(custom: false),
  HR(custom: false),
  HT(custom: false),
  HU(custom: false),
  ID(custom: false),
  IE(custom: false),
  IL(custom: false),
  IM(custom: false),
  IN(custom: false),
  IO(custom: false),
  IQ(custom: false),
  IR(custom: false),
  IS(custom: false),
  IT(custom: false),
  JE(custom: false),
  JM(custom: false),
  JO(custom: false),
  JP(custom: false),
  KE(custom: false),
  KG(custom: false),
  KH(custom: false),
  KI(custom: false),
  KM(custom: false),
  KN(custom: false),
  KP(custom: false),
  KR(custom: false),
  KW(custom: false),
  KY(custom: false),
  KZ(custom: false),
  LA(custom: false),
  LB(custom: false),
  LC(custom: false),
  LI(custom: false),
  LK(custom: false),
  LR(custom: false),
  LS(custom: false),
  LT(custom: false),
  LU(custom: false),
  LV(custom: false),
  LY(custom: false),
  MA(custom: false),
  MC(custom: false),
  MD(custom: false),
  ME(custom: false),
  MF(custom: false),
  MG(custom: false),
  MH(custom: false),
  MK(custom: false),
  ML(custom: false),
  MM(custom: false),
  MN(custom: false),
  MO(custom: false),
  MP(custom: false),
  MQ(custom: false),
  MR(custom: false),
  MS(custom: false),
  MT(custom: false),
  MU(custom: false),
  MV(custom: false),
  MW(custom: false),
  MX(custom: false),
  MY(custom: false),
  MZ(custom: false),
  NA(custom: false),
  NC(custom: false),
  NE(custom: false),
  NF(custom: false),
  NG(custom: false),
  NI(custom: false),
  NL(custom: false),
  NO(custom: false),
  NP(custom: false),
  NR(custom: false),
  NU(custom: false),
  NZ(custom: false),
  OM(custom: false),
  PA(custom: false),
  PE(custom: false),
  PF(custom: false),
  PG(custom: false),
  PH(custom: false),
  PK(custom: false),
  PL(custom: false),
  PM(custom: false),
  PN(custom: false),
  PR(custom: false),
  PS(custom: false),
  PT(custom: false),
  PW(custom: false),
  PY(custom: false),
  QA(custom: false),
  RE(custom: false),
  RO(custom: false),
  RS(custom: false),
  RU(custom: false),
  RW(custom: false),
  SA(custom: false),
  SB(custom: false),
  SC(custom: false),
  SD(custom: false),
  SE(custom: false),
  SG(custom: false),
  SH(custom: false),
  SI(custom: false),
  SJ(custom: false),
  SK(custom: false),
  SL(custom: false),
  SM(custom: false),
  SN(custom: false),
  SO(custom: false),
  SR(custom: false),
  SS(custom: false),
  ST(custom: false),
  SV(custom: false),
  SX(custom: false),
  SY(custom: false),
  SZ(custom: false),
  TC(custom: false),
  TD(custom: false),
  TF(custom: false),
  TG(custom: false),
  TH(custom: false),
  TJ(custom: false),
  TK(custom: false),
  TL(custom: false),
  TM(custom: false),
  TN(custom: false),
  TO(custom: false),
  TR(custom: false),
  TT(custom: false),
  TV(custom: false),
  TW(custom: false),
  TZ(custom: false),
  UA(custom: false),
  UG(custom: false),
  UM(custom: false),
  US(custom: false),
  UY(custom: false),
  UZ(custom: false),
  VA(custom: false),
  VC(custom: false),
  VE(custom: false),
  VG(custom: false),
  VI(custom: false),
  VN(custom: false),
  VU(custom: false),
  WF(custom: false),
  WS(custom: false),
  XK(custom: false),
  YE(custom: false),
  YT(custom: false),
  ZA(custom: false),
  ZM(custom: false),
  ZW(custom: false),
  DUMMY(custom: true),
  VIERKLEUR(custom: true);

  //
  //
  //

  final bool custom;

  //
  //
  //

  const CountryCode({required this.custom});

  //
  //
  //

  String get countryCode {
    final code = name.toLowerCase().replaceAll('_', '-');
    return code;
  }

  //
  //
  //

  String get assetPath {
    if (custom) {
      return 'packages/df_country_flags/assets/custom/svg/$countryCode.svg';
    }
    return 'packages/df_country_flags/assets/country-flags/svg/$countryCode.svg';
  }
}
